// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Identifier struct {
	ID        int64
	PartyID   int64
	Type      string
	Value     string
	CreatedAt sql.NullTime
}

type Party struct {
	ID        int64
	Name      string
	Location  sql.NullString
	CreatedAt sql.NullTime
}

type SaleBill struct {
	ID         int64
	BillNumber string
	BillDate   time.Time
	PartyName  string
	Amount     float64
	IsCashSale sql.NullBool
	CreatedAt  sql.NullTime
}

type Transaction struct {
	ID              int64
	PartyID         int64
	Amount          float64
	TransactionDate time.Time
	PaymentMode     sql.NullString
	Narration       sql.NullString
	Bank            string
	CreatedAt       sql.NullTime
}
