// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
)

const createParty = `-- name: CreateParty :one
INSERT INTO parties (name, location)
VALUES (?, ?)
RETURNING id, name, location, created_at
`

func (q *Queries) CreateParty(ctx context.Context, name string, location sql.NullString) (Party, error) {
	row := q.db.QueryRowContext(ctx, createParty, name, location)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const getPartyByID = `-- name: GetPartyByID :one
SELECT id, name, location, created_at FROM parties WHERE id = ?
`

func (q *Queries) GetPartyByID(ctx context.Context, id int64) (Party, error) {
	row := q.db.QueryRowContext(ctx, getPartyByID, id)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const getPartyByName = `-- name: GetPartyByName :one
SELECT id, name, location, created_at FROM parties WHERE name = ? LIMIT 1
`

func (q *Queries) GetPartyByName(ctx context.Context, name string) (Party, error) {
	row := q.db.QueryRowContext(ctx, getPartyByName, name)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const listParties = `-- name: ListParties :many
SELECT id, name, location, created_at FROM parties ORDER BY name
`

func (q *Queries) ListParties(ctx context.Context) ([]Party, error) {
	rows, err := q.db.QueryContext(ctx, listParties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Party
	for rows.Next() {
		var i Party
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createIdentifier = `-- name: CreateIdentifier :one
INSERT INTO identifiers (party_id, type, value)
VALUES (?, ?, ?)
ON CONFLICT (type, value) DO UPDATE SET party_id = excluded.party_id
RETURNING id, party_id, type, value, created_at
`

func (q *Queries) CreateIdentifier(ctx context.Context, partyID int64, identifierType string, value string) (Identifier, error) {
	row := q.db.QueryRowContext(ctx, createIdentifier, partyID, identifierType, value)
	var i Identifier
	err := row.Scan(
		&i.ID,
		&i.PartyID,
		&i.Type,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentifierByTypeValue = `-- name: GetIdentifierByTypeValue :one
SELECT id, party_id, type, value, created_at FROM identifiers WHERE type = ? AND value = ? LIMIT 1
`

func (q *Queries) GetIdentifierByTypeValue(ctx context.Context, identifierType string, value string) (Identifier, error) {
	row := q.db.QueryRowContext(ctx, getIdentifierByTypeValue, identifierType, value)
	var i Identifier
	err := row.Scan(
		&i.ID,
		&i.PartyID,
		&i.Type,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentifiersByPartyID = `-- name: GetIdentifiersByPartyID :many
SELECT id, party_id, type, value, created_at FROM identifiers WHERE party_id = ?
`

func (q *Queries) GetIdentifiersByPartyID(ctx context.Context, partyID int64) ([]Identifier, error) {
	rows, err := q.db.QueryContext(ctx, getIdentifiersByPartyID, partyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Identifier
	for rows.Next() {
		var i Identifier
		if err := rows.Scan(
			&i.ID,
			&i.PartyID,
			&i.Type,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPartiesByIdentifierValue = `-- name: FindPartiesByIdentifierValue :many
SELECT DISTINCT p.id, p.name, p.location, p.created_at, i.type as match_type, i.value as match_value
FROM parties p
JOIN identifiers i ON p.id = i.party_id
WHERE i.value = ?
`

func (q *Queries) FindPartiesByIdentifierValue(ctx context.Context, value string) ([]PartyWithMatch, error) {
	rows, err := q.db.QueryContext(ctx, findPartiesByIdentifierValue, value)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartyWithMatch
	for rows.Next() {
		var i PartyWithMatch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.CreatedAt,
			&i.MatchType,
			&i.MatchValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

func (q *Queries) FindPartiesByIdentifierValues(ctx context.Context, values []string) ([]PartyWithMatch, error) {
	if len(values) == 0 {
		return nil, nil
	}

	placeholders := make([]string, len(values))
	args := make([]interface{}, len(values))
	for i, v := range values {
		placeholders[i] = "?"
		args[i] = v
	}

	query := `SELECT DISTINCT p.id, p.name, p.location, p.created_at, i.type as match_type, i.value as match_value
FROM parties p
JOIN identifiers i ON p.id = i.party_id
WHERE i.value IN (` + strings.Join(placeholders, ",") + `)`

	rows, err := q.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartyWithMatch
	for rows.Next() {
		var i PartyWithMatch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.CreatedAt,
			&i.MatchType,
			&i.MatchValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (party_id, amount, transaction_date, payment_mode, narration)
VALUES (?, ?, ?, ?, ?)
RETURNING id, party_id, amount, transaction_date, payment_mode, narration, created_at
`

func (q *Queries) CreateTransaction(ctx context.Context, partyID int64, amount float64, transactionDate string, paymentMode sql.NullString, narration sql.NullString) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction, partyID, amount, transactionDate, paymentMode, narration)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.PartyID,
		&i.Amount,
		&i.TransactionDate,
		&i.PaymentMode,
		&i.Narration,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionsByPartyID = `-- name: GetTransactionsByPartyID :many
SELECT id, party_id, amount, transaction_date, payment_mode, narration, created_at FROM transactions
WHERE party_id = ?
ORDER BY transaction_date DESC
`

func (q *Queries) GetTransactionsByPartyID(ctx context.Context, partyID int64) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByPartyID, partyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.PartyID,
			&i.Amount,
			&i.TransactionDate,
			&i.PaymentMode,
			&i.Narration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTransactionsByPartyID = `-- name: CountTransactionsByPartyID :one
SELECT COUNT(*) as count FROM transactions WHERE party_id = ?
`

func (q *Queries) CountTransactionsByPartyID(ctx context.Context, partyID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionsByPartyID, partyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRecentTransactionsByPartyID = `-- name: GetRecentTransactionsByPartyID :many
SELECT id, party_id, amount, transaction_date, payment_mode, narration, created_at FROM transactions
WHERE party_id = ?
ORDER BY transaction_date DESC
LIMIT ?
`

func (q *Queries) GetRecentTransactionsByPartyID(ctx context.Context, partyID int64, limit int64) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getRecentTransactionsByPartyID, partyID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.PartyID,
			&i.Amount,
			&i.TransactionDate,
			&i.PaymentMode,
			&i.Narration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPartyWithTransactionCount = `-- name: GetPartyWithTransactionCount :one
SELECT p.id, p.name, p.location, p.created_at, COUNT(t.id) as transaction_count, COALESCE(SUM(t.amount), 0) as total_amount
FROM parties p
LEFT JOIN transactions t ON p.id = t.party_id
WHERE p.id = ?
GROUP BY p.id
`

func (q *Queries) GetPartyWithTransactionCount(ctx context.Context, id int64) (PartyWithStats, error) {
	row := q.db.QueryRowContext(ctx, getPartyWithTransactionCount, id)
	var i PartyWithStats
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
		&i.TransactionCount,
		&i.TotalAmount,
	)
	return i, err
}

const getAllPartiesWithStats = `-- name: GetAllPartiesWithStats :many
SELECT p.id, p.name, p.location, p.created_at, COUNT(t.id) as transaction_count, COALESCE(SUM(t.amount), 0) as total_amount
FROM parties p
LEFT JOIN transactions t ON p.id = t.party_id
GROUP BY p.id
ORDER BY transaction_count DESC
`

func (q *Queries) GetAllPartiesWithStats(ctx context.Context) ([]PartyWithStats, error) {
	rows, err := q.db.QueryContext(ctx, getAllPartiesWithStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartyWithStats
	for rows.Next() {
		var i PartyWithStats
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.CreatedAt,
			&i.TransactionCount,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
