// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countTransactionsByPartyID = `-- name: CountTransactionsByPartyID :one
SELECT COUNT(*) as count FROM transactions WHERE party_id = ?
`

func (q *Queries) CountTransactionsByPartyID(ctx context.Context, partyID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionsByPartyID, partyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIdentifier = `-- name: CreateIdentifier :one
INSERT INTO identifiers (party_id, type, value)
VALUES (?, ?, ?)
ON CONFLICT (type, value) DO UPDATE SET party_id = excluded.party_id
RETURNING id, party_id, type, value, created_at
`

type CreateIdentifierParams struct {
	PartyID int64
	Type    string
	Value   string
}

func (q *Queries) CreateIdentifier(ctx context.Context, arg CreateIdentifierParams) (Identifier, error) {
	row := q.db.QueryRowContext(ctx, createIdentifier, arg.PartyID, arg.Type, arg.Value)
	var i Identifier
	err := row.Scan(
		&i.ID,
		&i.PartyID,
		&i.Type,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const createParty = `-- name: CreateParty :one
INSERT INTO parties (name, location)
VALUES (?, ?)
RETURNING id, name, location, created_at
`

type CreatePartyParams struct {
	Name     string
	Location sql.NullString
}

func (q *Queries) CreateParty(ctx context.Context, arg CreatePartyParams) (Party, error) {
	row := q.db.QueryRowContext(ctx, createParty, arg.Name, arg.Location)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (party_id, amount, transaction_date, payment_mode, narration)
VALUES (?, ?, ?, ?, ?)
RETURNING id, party_id, amount, transaction_date, payment_mode, narration, created_at
`

type CreateTransactionParams struct {
	PartyID         int64
	Amount          float64
	TransactionDate time.Time
	PaymentMode     sql.NullString
	Narration       sql.NullString
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.PartyID,
		arg.Amount,
		arg.TransactionDate,
		arg.PaymentMode,
		arg.Narration,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.PartyID,
		&i.Amount,
		&i.TransactionDate,
		&i.PaymentMode,
		&i.Narration,
		&i.CreatedAt,
	)
	return i, err
}

const findPartiesByIdentifierValue = `-- name: FindPartiesByIdentifierValue :many
SELECT DISTINCT p.id, p.name, p.location, p.created_at, i.type as match_type, i.value as match_value
FROM parties p
JOIN identifiers i ON p.id = i.party_id
WHERE i.value = ?
`

type FindPartiesByIdentifierValueRow struct {
	ID         int64
	Name       string
	Location   sql.NullString
	CreatedAt  sql.NullTime
	MatchType  string
	MatchValue string
}

func (q *Queries) FindPartiesByIdentifierValue(ctx context.Context, value string) ([]FindPartiesByIdentifierValueRow, error) {
	rows, err := q.db.QueryContext(ctx, findPartiesByIdentifierValue, value)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPartiesByIdentifierValueRow
	for rows.Next() {
		var i FindPartiesByIdentifierValueRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.CreatedAt,
			&i.MatchType,
			&i.MatchValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPartiesByIdentifierValues = `-- name: FindPartiesByIdentifierValues :many
SELECT DISTINCT p.id, p.name, p.location, p.created_at, i.type as match_type, i.value as match_value
FROM parties p
JOIN identifiers i ON p.id = i.party_id
WHERE i.value IN (/*SLICE:values*/?)
`

type FindPartiesByIdentifierValuesRow struct {
	ID         int64
	Name       string
	Location   sql.NullString
	CreatedAt  sql.NullTime
	MatchType  string
	MatchValue string
}

func (q *Queries) FindPartiesByIdentifierValues(ctx context.Context, values []string) ([]FindPartiesByIdentifierValuesRow, error) {
	query := findPartiesByIdentifierValues
	var queryParams []interface{}
	if len(values) > 0 {
		for _, v := range values {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:values*/?", strings.Repeat(",?", len(values))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:values*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPartiesByIdentifierValuesRow
	for rows.Next() {
		var i FindPartiesByIdentifierValuesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.CreatedAt,
			&i.MatchType,
			&i.MatchValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPartiesByNarrationPattern = `-- name: FindPartiesByNarrationPattern :many
SELECT DISTINCT p.id, p.name, p.location, p.created_at, t.narration as match_narration
FROM parties p
JOIN transactions t ON p.id = t.party_id
WHERE t.narration LIKE ?
LIMIT 50
`

type FindPartiesByNarrationPatternRow struct {
	ID             int64
	Name           string
	Location       sql.NullString
	CreatedAt      sql.NullTime
	MatchNarration sql.NullString
}

func (q *Queries) FindPartiesByNarrationPattern(ctx context.Context, narration sql.NullString) ([]FindPartiesByNarrationPatternRow, error) {
	rows, err := q.db.QueryContext(ctx, findPartiesByNarrationPattern, narration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPartiesByNarrationPatternRow
	for rows.Next() {
		var i FindPartiesByNarrationPatternRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.CreatedAt,
			&i.MatchNarration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPartiesWithStats = `-- name: GetAllPartiesWithStats :many
SELECT p.id, p.name, p.location, p.created_at, COUNT(t.id) as transaction_count, COALESCE(SUM(t.amount), 0) as total_amount
FROM parties p
LEFT JOIN transactions t ON p.id = t.party_id
GROUP BY p.id
ORDER BY transaction_count DESC
`

type GetAllPartiesWithStatsRow struct {
	ID               int64
	Name             string
	Location         sql.NullString
	CreatedAt        sql.NullTime
	TransactionCount int64
	TotalAmount      interface{}
}

func (q *Queries) GetAllPartiesWithStats(ctx context.Context) ([]GetAllPartiesWithStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPartiesWithStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPartiesWithStatsRow
	for rows.Next() {
		var i GetAllPartiesWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.CreatedAt,
			&i.TransactionCount,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdentifierByTypeValue = `-- name: GetIdentifierByTypeValue :one
SELECT id, party_id, type, value, created_at FROM identifiers WHERE type = ? AND value = ? LIMIT 1
`

type GetIdentifierByTypeValueParams struct {
	Type  string
	Value string
}

func (q *Queries) GetIdentifierByTypeValue(ctx context.Context, arg GetIdentifierByTypeValueParams) (Identifier, error) {
	row := q.db.QueryRowContext(ctx, getIdentifierByTypeValue, arg.Type, arg.Value)
	var i Identifier
	err := row.Scan(
		&i.ID,
		&i.PartyID,
		&i.Type,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentifiersByPartyID = `-- name: GetIdentifiersByPartyID :many
SELECT id, party_id, type, value, created_at FROM identifiers WHERE party_id = ?
`

func (q *Queries) GetIdentifiersByPartyID(ctx context.Context, partyID int64) ([]Identifier, error) {
	rows, err := q.db.QueryContext(ctx, getIdentifiersByPartyID, partyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Identifier
	for rows.Next() {
		var i Identifier
		if err := rows.Scan(
			&i.ID,
			&i.PartyID,
			&i.Type,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPartyByID = `-- name: GetPartyByID :one
SELECT id, name, location, created_at FROM parties WHERE id = ?
`

func (q *Queries) GetPartyByID(ctx context.Context, id int64) (Party, error) {
	row := q.db.QueryRowContext(ctx, getPartyByID, id)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const getPartyByName = `-- name: GetPartyByName :one
SELECT id, name, location, created_at FROM parties WHERE name = ? LIMIT 1
`

func (q *Queries) GetPartyByName(ctx context.Context, name string) (Party, error) {
	row := q.db.QueryRowContext(ctx, getPartyByName, name)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const getPartyWithTransactionCount = `-- name: GetPartyWithTransactionCount :one
SELECT p.id, p.name, p.location, p.created_at, COUNT(t.id) as transaction_count, SUM(t.amount) as total_amount
FROM parties p
LEFT JOIN transactions t ON p.id = t.party_id
WHERE p.id = ?
GROUP BY p.id
`

type GetPartyWithTransactionCountRow struct {
	ID               int64
	Name             string
	Location         sql.NullString
	CreatedAt        sql.NullTime
	TransactionCount int64
	TotalAmount      sql.NullFloat64
}

func (q *Queries) GetPartyWithTransactionCount(ctx context.Context, id int64) (GetPartyWithTransactionCountRow, error) {
	row := q.db.QueryRowContext(ctx, getPartyWithTransactionCount, id)
	var i GetPartyWithTransactionCountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
		&i.TransactionCount,
		&i.TotalAmount,
	)
	return i, err
}

const getRecentTransactionsByPartyID = `-- name: GetRecentTransactionsByPartyID :many
SELECT id, party_id, amount, transaction_date, payment_mode, narration, created_at FROM transactions
WHERE party_id = ?
ORDER BY transaction_date DESC
LIMIT ?
`

type GetRecentTransactionsByPartyIDParams struct {
	PartyID int64
	Limit   int64
}

func (q *Queries) GetRecentTransactionsByPartyID(ctx context.Context, arg GetRecentTransactionsByPartyIDParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getRecentTransactionsByPartyID, arg.PartyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.PartyID,
			&i.Amount,
			&i.TransactionDate,
			&i.PaymentMode,
			&i.Narration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByPartyID = `-- name: GetTransactionsByPartyID :many
SELECT id, party_id, amount, transaction_date, payment_mode, narration, created_at FROM transactions
WHERE party_id = ?
ORDER BY transaction_date DESC
`

func (q *Queries) GetTransactionsByPartyID(ctx context.Context, partyID int64) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByPartyID, partyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.PartyID,
			&i.Amount,
			&i.TransactionDate,
			&i.PaymentMode,
			&i.Narration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParties = `-- name: ListParties :many
SELECT id, name, location, created_at FROM parties ORDER BY name
`

func (q *Queries) ListParties(ctx context.Context) ([]Party, error) {
	rows, err := q.db.QueryContext(ctx, listParties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Party
	for rows.Next() {
		var i Party
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
